language: java
jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6
script: mvn compile test
install: true
notifications:
  irc: 
    channels: 
      - "irc.spi.gt#essentials-dev"
    on_success: change
    on_failure: always
  email:
    recipients:
      - "paul+essentials@earth2me.com"
    on_success: change
    on_failure: always